services:
  - type: web
    name: inventory-tracker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DB_HOST
        value: sql12.freesqldatabase.com
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: sql12789125
      - key: DB_USER
        value: sql12789125
      - key: DB_PASSWORD
        value: ujcpYqUhIM
